### Get all boats

GET http://localhost:8080/api/boats

### Get single boat

GET http://localhost:8080/api/boats/f08ef7e3-7f2a-4378-b1fb-2922d730c70d

### Get single boat, not existing

GET http://localhost:8080/api/characters/3c6f1eb1-8069-44ab-988f-d7fed2b65d87

### Get boatType boats

GET http://localhost:8080/api/boatTypes/5d1da2ae-6a14-4b6d-8b4f-d117867118d4/boats

### Get profession characters, not existing

GET http://localhost:8080/api/boatTypes/ac4e2683-b2ba-4695-94d9-806a97fce71e/boats

### Create new character

PUT http://localhost:8080/api/boats/3c6f1eb1-8069-44ab-988f-d7fed2b65d83
Content-Type: application/json
Authorization: Basic a2V2aW46dXNlcnVzZXI=

{
  "name": "Lotka",
  "sailArea": 10,
  "boatType": "2d9b1e8c-67c5-4188-a911-5f064a63d8cd"
}

### Delete character.

DELETE http://localhost:8080/api/boats/f08ef7e3-7f2a-4378-b1fb-2922d730c70d

### Get all boatTypes

GET http://localhost:8080/api/boatTypes

### Get single boatType

GET http://localhost:8080/api/boatTypes/2d9b1e8c-67c5-4188-a911-5f064a63d8cd

### Get single boatType, not existing

GET http://localhost:8080/api/boatTypes/ac4e2683-b2ba-4695-94d9-806a97fce71e

### Delete boatType

DELETE http://localhost:8080/api/boatTypes/2d9b1e8c-67c5-4188-a911-5f064a63d8cd